package com.dance.street.game.domain;

import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.dromara.common.tenant.core.TenantEntity;

import java.io.Serial;
import java.math.BigDecimal;

/**
 * 赛段名单来源组 {@code t_stage_roster_group}:赛段间依赖的"边 + 取人规则"。
 *
 * <p>一行 = 一条出口/入边({@code sourceStageId → targetStageId}),图上的分叉 = 同 source 多行、
 * 汇合 = 同 target 多行、平行边 = 同一对节点之间按圈/名次段切分的多行。</p>
 *
 * <p>关键语义位:</p>
 * <ul>
 *   <li>{@code autoGenerated}(列 {@code auto_generated}):1 = 建段时系统自动补的链式衔接。
 *       按<b>出处</b>判断,不再按字段长相猜({@code isGeneratedDefault});删掉即永久生效,不再自动补回。</li>
 * </ul>
 *
 * <p>边之间没有先后语义:座位由来源赛段给出的座号决定,取人顺序不影响落座。</p>
 *
 * @author duane
 */
@Data
@EqualsAndHashCode(callSuper = true)
@TableName("t_stage_roster_group")
public class TStageRosterGroup extends TenantEntity {

    @Serial
    private static final long serialVersionUID = 1L;

    @TableId(value = "id")
    private Long id;

    private Long tournamentId;

    /** 入边:这条规则把谁带进哪个赛段 */
    private Long targetStageId;

    /** 来源赛段;NULL = 外部签到/报名 */
    private Long sourceStageId;

    /** ADVANCE/ELIMINATED/ANY/WITHDRAWN/PENDING */
    private String resultFilter;

    /** 圈过滤,如 ZONE-1 */
    private String zone;

    /** 淘汰赛第几轮(display_row) */
    private Integer roundNo;

    private Integer rankStart;

    private Integer rankEnd;

    /** 1 = 名次取圈内名次(rank_in_match);0 = 赛段全局名次(final_rank) */
    private Integer rankByZone;

    private BigDecimal scoreMin;

    private BigDecimal scoreMax;

    /** AUTO/MANUAL/STREAM */
    private String fillMode;

    /** 本组取人上限,0 = 不限 */
    private Integer quota;

    /** 组内排序键 */
    private String orderBy;

    /**
     * 1 = 建段时系统自动补的链式衔接。
     *
     * <p>属性名故意叫 {@code autoGenerated} 而不是 {@code generated}:MySQL 8 把
     * {@code GENERATED} 当保留字,列名裸写会报 1064;而 MyBatis-Plus 在没有
     * {@code @TableField} 时按"驼峰转下划线"映射,属性名不是列的驼峰形式时还会补一个
     * {@code 列 AS 属性名} 的别名,那个别名同样撞保留字。属性名与列名同源后,
     * 查询 SQL 里既没有保留字列名,也没有保留字别名。</p>
     *
     * <p>对外接口字段仍是 {@code generated}(见 {@code TStageRosterGroupBo}),前端不受影响。</p>
     */
    private Integer autoGenerated;

    private String remark;
}
